# print('Now I need money')
# input('Give me money')
# money = input('Give me some money: ')
# print('here is your money',money)
first_money = input('kodom Ali,dosto kichu taka de: ')
second_money = input('Peyara Begum,apu kichu taka de: ')
print(first_money,second_money)